[package]
name = "short_cuts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
savefile = "0.10.1"
savefile-derive="0.10"